spring:
  application:
    name: py
server:
  port: 8130
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
#        以下是我用手机热点部署，注意docker内的内网ip每个都不同，需要 cat /etc/hosts
#      http://192.168.43.38:8761/eureka/,http://192.168.43.38:8762/eureka/
# ????
ribbon:
#  eureka:
#    enabled: false
  ConnectTimeout: 10000
  ReadTimeOut: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000



#监听python
sidecar:
  port: 5000
  health-uri: http://localhost:${sidecar.port}/health
#  http://192.168.43.38:${sidecar.port}/health
